CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email VARCHAR NOT NULL UNIQUE,
                                     login VARCHAR NOT NULL,
                                     name VARCHAR,
                                     birthday VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS rating (
                                      rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      name VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS films (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR NOT NULL,
                                     description VARCHAR NOT NULL,
                                     release_date VARCHAR NOT NULL,
                                     duration BIGINT NOT NULL,
                                     rating_id INTEGER NOT NULL,
                                     CONSTRAINT fk_films_rating FOREIGN KEY (rating_id) REFERENCES rating(rating_id)
    );

CREATE TABLE IF NOT EXISTS genres (
                                      genre_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      name VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS genre_id_film_id (
                                                film_id BIGINT,
                                                genre_id BIGINT,
                                                PRIMARY KEY (film_id, genre_id),
    CONSTRAINT fk_genre_film_films FOREIGN KEY (film_id) REFERENCES films(id),
    CONSTRAINT fk_genre_film_genres FOREIGN KEY (genre_id) REFERENCES genres(genre_id)
    );

CREATE TABLE IF NOT EXISTS likes (
                                     film_id BIGINT,
                                     user_id BIGINT,
                                     PRIMARY KEY (film_id, user_id),
    CONSTRAINT fk_likes_films FOREIGN KEY (film_id) REFERENCES films(id),
    CONSTRAINT fk_likes_users FOREIGN KEY (user_id) REFERENCES users(id)
    );

CREATE TABLE IF NOT EXISTS friendship (
                                          inviter_id BIGINT,
                                          acceptor_id BIGINT,
                                          confirmation_status BOOLEAN NOT NULL DEFAULT FALSE,
                                          PRIMARY KEY (inviter_id, acceptor_id),
    CONSTRAINT fk_friendship_inviter FOREIGN KEY (inviter_id) REFERENCES users(id),
    CONSTRAINT fk_friendship_acceptor FOREIGN KEY (acceptor_id) REFERENCES users(id)
    );